apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: lb-ng-gke
  name: sep6-angular-gke
spec:
  type: LoadBalancer
  ports:
    - name: sep6-angular-gke
      port: 80
      protocol: TCP
  selector:
    app: sep6-angular-gke
