apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: lb-sep6-angular-gke
  name: sep6-angular-gke
spec:
  selector:
    app: sep6-angular-gke
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 4200
